version: '3.3'
  
services:
   db:
     container_name: mysql-server     
     image: mariadb:10.6.21
     command: --character-set-server=utf8 --collation-server=utf8_bin --default-authentication-plugin=mysql_native_password
     restart: always
     volumes:
             - db_data:/var/lib/mysql
               #             - ./mycustom.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
     networks:
             - zabbix-net
     environment:
       MYSQL_DATABASE: &db_database zabbix
       MYSQL_USER: &db_user zabbix
       MYSQL_PASSWORD: &db_pswd 123456
       MYSQL_ROOT_PASSWORD: &db_root_pswd 123456
   zabbix-java-gw:
     container_name: zabbix-java-gateway
     image: zabbix/zabbix-java-gateway:7.2.7-alpine
     restart: always
     networks:
             - zabbix-net
   zabbix-server:
     container_name: zabbix-server-mysql
     depends_on:
             - db
     image: zabbix/zabbix-server-mysql:7.2.7-alpine
     restart: always
     networks:
             - zabbix-net
     ports: 
             - 10051:10051
     environment:
       TZ: Asia/Beijing
       DB_SERVER_HOST: mysql-server
       ZBX_JAVAGATEWAY: zabbix-java-gateway
       ZBX_CACHESIZE: 8G
       ZBX_HISTORYCACHESIZE: 1G
       ZBX_TRENDCACHESIZE: 256M
       ZBX_VALUECACHESIZE: 1G
       ZBX_STARTPOLLERS: 80
       MYSQL_DATABASES: *db_database
       MYSQL_USER: *db_user
       MYSQL_PASSWORD: *db_pswd
       MYSQL_ROOT_PASSWORD: *db_root_pswd
   zabbix-web:
     container_name: zabbix-web-nginx-mysql     
     depends_on:
             - zabbix-server
     image: zabbix/zabbix-web-nginx-mysql:7.2.7-alpine
     restart: always
     networks:
             - zabbix-net
     ports: 
             - 8888:8080
     environment:
       ZBX_SERVER_HOST: zabbix-server-mysql
       DB_SERVER_HOST: mysql-server
       MYSQL_DATABASES: *db_database
       MYSQL_USER: *db_user
       MYSQL_PASSWORD: *db_pswd
       MYSQL_ROOT_PASSWORD: *db_root_pswd
#    grafana-web:
#      container_name: grafana-web
#      depends_on:
#              - zabbix-server
#              - db
#      image: grafana/grafana:latest
#      restart: always
#      volumes:
#              - grafana_storage:/var/lib/grafana
#      networks:
#              - zabbix-net
#      ports:
#              - 3000:3000
volumes:
    db_data:
      driver: local
      driver_opts:
          type: none
          device: ${PWD}/db_data
          o: bind
    grafana_storage:
      driver: local
      driver_opts:
          type: none
          device: ${PWD}/grafana_storage
          o: bind
networks:
    zabbix-net: {}  

